### ISSUE TITLE
Setup & Running

### ISSUE THREAD

**Issue by snisnik** [tejpshah/interview-pilot-ai#1]
Hey mate how are you? Can you share the steps to run this locally?

**Comment by tejpshah** [comment]
Hey! Sorry about having no setup instructions here. 

I'll try to get to this soon for the setup instructions. 

cc: @JinalShah2002

**Comment by JinalShah2002** [comment]
Hey! Will have some instructions out soon!

**Comment by JinalShah2002** [comment]
Updated  the ReadMe to include set-up instructions. Please shoot me a message if they don't work!
